-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.login
(
    id integer NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT login_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.login
    ALTER COLUMN id
    SET (n_distinct=1);

CREATE TABLE IF NOT EXISTS public.login_admin
(
    id integer NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT login_admin_pkey PRIMARY KEY (id)
);
END;